# Generated by Django 4.2.5 on 2023-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('dia_reserva', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
